import siteMetadata from '@/data/siteMetadata'
import Link from '@/components/Link'
import { PageSEO } from '@/components/SEO'

export default function Projects() {
  return (
    <>
      <PageSEO title={`Cookie Policy - ${siteMetadata.author}`} description={`Qui troverai tutte le informazioni su come sono arrivato a svolgere questo lavoro e cosa mi ha portato a diventare un SEO Specialist!`} />
      <div className="divide-y divide-gray-200 dark:divide-gray-700">
<h1 class="cookie-policy-h1">Cookie Policy</h1>
<p>
    Effective Date: 09-Nov-2022 <br/>
    Last Updated: 09-Nov-2022
</p>

&nbsp;
<h5>What are cookies?</h5>
<div class="cookie-policy-p"><p>This Cookie Policy explains what cookies are and how we use them, the types of cookies we use i.e, the information we collect using cookies and how that information is used, and how to manage the cookie settings.</p> <p>Cookies are small text files that are used to store small pieces of information. They are stored on your device when the website is loaded on your browser. These cookies help us make the website function properly, make it more secure, provide better user experience, and understand how the website performs and to analyze what works and where it needs improvement.</p></div>

&nbsp;
<h5>How do we use cookies?</h5>
<div class="cookie-policy-p"><p>As most of the online services, our website uses first-party and third-party cookies for several purposes. First-party cookies are mostly necessary for the website to function the right way, and they do not collect any of your personally identifiable data.</p> <p>The third-party cookies used on our website are mainly for understanding how the website performs, how you interact with our website, keeping our services secure, providing advertisements that are relevant to you, and all in all providing you with a better and improved user experience and help speed up your future interactions with our website.</p></div>

&nbsp;
    <h5>Tipi di Cookie che utilizziamo</h5>

    <div class="cky-audit-table-element"></div>

&nbsp;
    <h5 style="margin-bottom:20px;">Gestisci le preferenze sui cookie</h5>

    <a class="cky-banner-element">Impostazioni dei Cookie</a> <br/>

    <div><p>Puoi modificare le tue preferenze sui cookie in qualsiasi momento facendo clic sul pulsante sopra. Questo ti consentirà di rivedere il banner di consenso ai cookie e modificare le tue preferenze o revocare immediatamente il tuo consenso.</p><p>Oltre a ciò, diversi browser forniscono diversi metodi per bloccare ed eliminare i cookie utilizzati dai siti web. Puoi modificare le impostazioni del tuo browser per bloccare/eliminare i cookie. Di seguito sono elencati i link ai documenti di supporto su come gestire ed eliminare i cookie dai principali browser web.</p><p>Chrome: <a target="_blank" rel="noopener noreferrer" href="https://support.google.com/accounts/answer/32050">https://support.google.com/accounts/answer/32050</a></p><p>Safari: <a target="_blank" rel="noopener noreferrer" href="https://support.apple.com/en-in/guide/safari/sfri11471/mac">https://support.apple.com/en-in/guide/safari/sfri11471/mac</a></p><p>Firefox: <a target="_blank" rel="noopener noreferrer" href="https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectslug=delete-cookies-remove-info-websites-stored&amp;redirectlocale=en-US">https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectslug=delete-cookies-remove-info-websites-stored&amp;redirectlocale=en-US</a></p><p>Internet Explorer: <a target="_blank" rel="noopener noreferrer" href="https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc">https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc</a></p><p>Se stai utilizzando un qualsiasi altro browser web, visita i documenti di supporto ufficiali del tuo browser.</p></div>


&nbsp;
<p class="cookie-policy-p">
    Cookie Policy Generated By  <a target="_blank" href="https://www.cookieyes.com/?utm_source=CP&utm_medium=footer&utm_campaign=UW">CookieYes - Cookie Policy Generator</a>.
</p>
      </div>
    </>
  )
}